name: openwrt-mt798x-cache

on:
  workflow_dispatch:
    inputs:
      repo:
        description: "选择源码仓库"
        required: true
        default: "hanwckf"
        type: choice
        options:
          - hanwckf
          - padavanonly
          - NekokeCore

jobs:
  build:
    name: ${{ matrix.model }}-${{ matrix.repo }}
    runs-on: ubuntu-22.04
    env:
      REPO_URL: ${{ matrix.repo_url }}
      REPO_BRANCH: ${{ matrix.repo_branch }}
      CONFIG_FILE: configs/${{ matrix.model }}.config
      FIRMWARE_RELEASE: true
      FIRMWARE_TAG: ${{ matrix.repo_branch }}
      TZ: Asia/Shanghai
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        model:
          - mt7981
          - mt7986
        repo: [hanwckf, padavanonly, nekoke]
        include:
          - repo: hanwckf
            repo_url: https://github.com/hanwckf/immortalwrt-mt798x
            repo_branch: openwrt-21.02
          - repo: padavanonly
            repo_url: https://github.com/padavanonly/immortalwrt-mt798x-23.05
            repo_branch: openwrt-23.05
          - repo: nekoke
            repo_url: https://github.com/NekokeCore/immortalwrt-mt798x-24.10
            repo_branch: openwrt-24.10

    steps:
    - name: Check Server Performance
      run: |
        echo "警告⚠"
        echo "分配的服务器性能有限，若选择的插件过多，务必注意CPU性能！"
        echo -e "已知CPU型号(降序): 7763，8370C，8272CL，8171M，E5-2673\n"
        echo "--------------------------CPU信息--------------------------"
        echo "CPU物理数量: $(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
        echo "CPU核心数量: $(nproc)"
        echo -e "CPU型号信息:$(cat /proc/cpuinfo | grep -m1 name | awk -F: '{print $2}')\n"
        echo "--------------------------内存信息--------------------------"
        echo "已安装内存详细信息:"
        echo -e "$(sudo lshw -short -C memory | grep GiB)\n"
        echo "--------------------------硬盘信息--------------------------"
        echo "硬盘数量: $(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT

    - name: Initialization Environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        docker rmi $(docker images -q)
        sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d /usr/local/lib/android $AGENT_TOOLSDIRECTORY
        sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby* || true
        sudo -E apt-get -y update
        sudo -E apt-get -y install $(curl -fsSL https://git.kejizero.online/zhao/files/raw/branch/main/Rely/ubuntu2204)
        sudo -E systemctl daemon-reload
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get -y clean
        sudo timedatectl set-timezone "$TZ"

    - name: Combine Disks
      uses: easimon/maximize-build-space@master
      with:
        swap-size-mb: 1024
        temp-reserve-mb: 100
        root-reserve-mb: 1024

    - name: Checkout
      uses: actions/checkout@main

    - name: Clone Source Code
      run: |
        df -hT $GITHUB_WORKSPACE
        git clone $REPO_URL -b $REPO_BRANCH openwrt
        cd openwrt
        echo "OPENWRT_PATH=$PWD" >> $GITHUB_ENV
        COMMIT_AUTHOR=$(git show -s --date=short --format="作者: %an")
        echo "COMMIT_AUTHOR=$COMMIT_AUTHOR" >> $GITHUB_ENV
        COMMIT_DATE=$(git show -s --date=short --format="时间: %ci")
        echo "COMMIT_DATE=$COMMIT_DATE" >> $GITHUB_ENV
        COMMIT_MESSAGE=$(git show -s --date=short --format="内容: %s")
        echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
        COMMIT_HASH=$(git show -s --date=short --format="hash: %H")
        echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV

    - name: Generate Variables
      run: |
        cp $CONFIG_FILE $OPENWRT_PATH/.config
        cd $OPENWRT_PATH
        make defconfig > /dev/null 2>&1
        SOURCE_REPO="$(echo $REPO_URL | awk -F '/' '{print $(NF)}')"
        echo "SOURCE_REPO=$SOURCE_REPO" >> $GITHUB_ENV
        DEVICE_TARGET=$(cat .config | grep CONFIG_TARGET_BOARD | awk -F '"' '{print $2}')
        echo "DEVICE_TARGET=$DEVICE_TARGET" >> $GITHUB_ENV
        DEVICE_SUBTARGET=$(cat .config | grep CONFIG_TARGET_SUBTARGET | awk -F '"' '{print $2}')
        echo "DEVICE_SUBTARGET=$DEVICE_SUBTARGET" >> $GITHUB_ENV

    - name: Install Feeds
      run: |
        cd $OPENWRT_PATH
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Download DL Package
      run: |
        cd $OPENWRT_PATH
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile Firmware
      id: compile
      run: |
        cd $OPENWRT_PATH
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 || make -j1 V=s
        echo "status=success" >> $GITHUB_OUTPUT
        echo "DATE=$(date +"%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV
        echo "FILE_DATE=$(date +"%Y.%m.%d")" >> $GITHUB_ENV

    - name: Check Space Usage
      if: (!cancelled())
      run: df -hT

- name: Organize Files
  if: steps.compile.outputs.status == 'success'
  run: |
    cd $OPENWRT_PATH
    case "$SOURCE_REPO" in
      "hanwckf") CACHE_NAME="openwrt-hanwckf-${{ matrix.model }}.tar.gz" ;;
      "padavanonly") CACHE_NAME="openwrt-padavanonly-${{ matrix.model }}.tar.gz" ;;
      "NekokeCore") CACHE_NAME="openwrt-nekokecore-${{ matrix.model }}.tar.gz" ;;
      *) CACHE_NAME="openwrt-${SOURCE_REPO}-${{ matrix.model }}.tar.gz" ;;
    esac
    echo "CACHE_NAME=$CACHE_NAME" >> $GITHUB_ENV
    tar -czf $CACHE_NAME staging_dir build_dir dl tmp

- name: Upload Firmware To Release
  if: steps.compile.outputs.status == 'success' && env.FIRMWARE_RELEASE == 'true'
  uses: ncipollo/release-action@v1
  with:
    name: ${{ env.FIRMWARE_TAG }}
    allowUpdates: true
    tag: ${{ env.FIRMWARE_TAG }}
    token: ${{ secrets.GITHUB_TOKEN }}
    artifacts: $OPENWRT_PATH/${{ env.CACHE_NAME }}
