name: openwrt-24.10-cache

on:
  workflow_dispatch:
    inputs:
      device:
        description: 'Select the build device'
        required: true
        default: 'x86_64'
        type: choice
        options:
          - 'rockchip'
          - 'mt798x'
          - 'ipq807x'
          - 'ipq50xx'
          - 'x86_64'
