name: openwrt-24.10-gcc13

on: workflow_dispatch

jobs:
  build:
    name: ${{ matrix.model }}-${{ matrix.libc }}
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        model:
          - Rockchip
          - MT798x
          - X86_64
          - IPQ_807x

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Set time zone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'

    - name: Show system
      run: |
        lscpu
        free -h
        df -Th
        uname -a
